#define MAX_POCKET_WEIGHT     30
#define MAX_TRASHBIN_WEIGHT   30
#define MAX_SAFE_WEIGHT       30
#define MAX_SAFE_MONEY        50000

#define MAX_INVENTORY_ITEMS   100
#define MAX_DROPPED_ITEMS     4000
#define MAX_REPORTS       	  100
#define MAX_EMERGENCY       	  1000
#define MAX_APBS              50
#define MAX_LISTED_BANS       10
#define MAX_HOUSES            1000
#define MAX_COMPANIES         500
#define MAX_PRODUCTS          20
#define MAX_ITEM_NAME         32
#define MAX_RESTAURANT_ITEMS  10
#define MAX_BUILDINGS         700
#define MAX_FURNITURE         7500
#define MAX_CARS              1800
#define MAX_STORED_ITEMS      100000
#define MAX_BANK_ACCOUNTS     5
#define MAX_ACCESSORIES       5
#define MAX_GAS_PUMPS         100
#define MAX_ATMS              50
#define MAX_DEALERSHIP_CARS   1000
#define MAX_SHELL_CASINGS     1000
#define MAX_BLOOD             1000
#define MAX_WEEDPLANTS        1000
#define MAX_FACTIONS          20
#define MAX_FACTION_RANKS     20
#define MAX_RANK_NAME         32
#define MAX_ARREST_POINTS     10
#define MAX_FACTION_UNIFORMS  20
#define MAX_ADMIN_TELEPORTS   100
#define MAX_GATES             200
#define MAX_DYNAMIC_LABELS    40
#define MAX_AUTO_SHOPS        20
#define MAX_DEPLOYED_ITEMS    50
#define MAX_SCRIPT_OBJECTS    5000
#define MAX_TRASH_BINS        100
#define MAX_SPRAY_TAGS        100
#define MAX_TAGS              100
#define MAX_PAYPHONES         100
#define MAX_LOCKERS           100
#define MAX_LOCKER_SKINS      20
#define MAX_LOCKER_ITEMS      20
#define MAX_FACTION_EQUIPMENT 20
#define MAX_FACTION_ACCESSORIES 20
#define MAX_CCTV 100
#define MAX_CCTV_NAME 50
